name: CI

on: [push]

jobs:

  
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run:
          docker build -t ghcr.io/sagr0m/24-noyab:1.0 .
          docker push ghcr.io/sagr0m/24-noyab:1.0
